
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.6.1
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 1.6894  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.019744   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global	         EREST_ACT	-0.065  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.065  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*set_compt_param     ELEAK -0.065  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.39147064  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
Seg0_soma none 0 0 0 16.15439 -4.901365 -0.021689 4.971291 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_soma Seg0_soma 32.30877 -9.802731 -0.043378 9.14839 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_0 Seg1_soma 0.625 1.265941 -2.086622 -4.277443 4.325438 -2.397231 3.495449 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_0 Seg0_apic_0 -9.179887 7.384937 -2.70784 3.158364 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_13 Seg1_soma 9.215002 -7.924059 -11.78662 4.742506 -20.44825 -18.65124 1.937473 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_13 Seg0_dend_13 0.270009 -32.97243 -25.51587 1.909594 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_6 Seg1_soma 20.055 2.37594 -11.13662 36.67439 13.3212 -21.65471 1.302139 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_6 Seg0_dend_6 53.29377 24.26645 -32.17279 1.247891 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_0 Seg1_soma 23.315 -3.31406 -5.286622 21.4194 -0.04196239 -7.06557 1.371425 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_0 Seg0_dend_0 19.5238 3.230135 -8.844518 1.554899 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_29__Extra_0 Seg1_apic_0 -8.844997 7.175941 -2.686622 -25.50811 0.06687069 -1.326403 1.061723 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_29__Extra_1 Seg0_apic_29__Extra_0 -42.17122 -7.042199 0.0338161 1.061723 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_29__Extra_2 Seg0_apic_29__Extra_1 -58.83433 -14.15127 1.394035 1.061723 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_29 Seg0_apic_29__Extra_2 -75.49744 -21.26034 2.754254 1.061723 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_29__Extra_0 Seg0_apic_29 -92.16055 -28.36941 4.114473 0.8985249 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_29__Extra_1 Seg1_apic_29__Extra_0 -108.8237 -35.47848 5.474692 0.8985249 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_29__Extra_2 Seg1_apic_29__Extra_1 -125.4868 -42.58755 6.834911 0.8985249 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_29 Seg1_apic_29__Extra_2 -142.1499 -49.69661 8.19513 0.8985249 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_1__Extra_0 Seg1_apic_0 -8.844997 7.175941 -2.686622 -38.1049 20.4324 -1.87688 2.132916 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_1__Extra_1 Seg0_apic_1__Extra_0 -67.36481 33.68885 -1.067138 2.132916 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_1__Extra_2 Seg0_apic_1__Extra_1 -96.62472 46.94532 -0.2573959 2.132916 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_1__Extra_3 Seg0_apic_1__Extra_2 -125.8846 60.20177 0.5523461 2.132916 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_1 Seg0_apic_1__Extra_3 -155.1445 73.45823 1.362088 2.132916 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_1__Extra_0 Seg0_apic_1 -184.4044 86.71468 2.17183 1.59193 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_1__Extra_1 Seg1_apic_1__Extra_0 -213.6643 99.97115 2.981572 1.59193 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_1__Extra_2 Seg1_apic_1__Extra_1 -242.9242 113.2276 3.791314 1.59193 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_1__Extra_3 Seg1_apic_1__Extra_2 -272.1841 126.4841 4.601056 1.59193 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_1 Seg1_apic_1__Extra_3 -301.444 139.7405 5.410798 1.59193 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_17__Extra_0 Seg1_dend_13 1.755001 -28.81406 -23.23662 8.843566 -48.76048 -30.93239 0.9405233 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_17__Extra_1 Seg0_dend_17__Extra_0 15.93213 -68.7069 -38.62816 0.9405233 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_17__Extra_2 Seg0_dend_17__Extra_1 23.02069 -88.65332 -46.32393 0.9405233 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_17__Extra_3 Seg0_dend_17__Extra_2 30.10926 -108.5997 -54.0197 0.9405233 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_17 Seg0_dend_17__Extra_3 37.19782 -128.5462 -61.71547 0.9405233 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_17__Extra_0 Seg0_dend_17 44.28639 -148.4926 -69.41124 0.8291665 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_17__Extra_1 Seg1_dend_17__Extra_0 51.37495 -168.439 -77.10701 0.8291665 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_17__Extra_2 Seg1_dend_17__Extra_1 58.46351 -188.3854 -84.80278 0.8291665 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_17__Extra_3 Seg1_dend_17__Extra_2 65.55208 -208.3318 -92.49855 0.8291665 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_17 Seg1_dend_17__Extra_3 72.64064 -228.2782 -100.1943 0.8291665 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_14__Extra_0 Seg1_dend_13 1.755001 -28.81406 -23.23662 -7.271262 -51.3267 -28.24255 1.342591 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_14 Seg0_dend_14__Extra_0 -16.29753 -73.83933 -33.24847 1.342591 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_14__Extra_0 Seg0_dend_14 -25.32379 -96.35197 -38.2544 1.502127 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_14 Seg1_dend_14__Extra_0 -34.35005 -118.8646 -43.26033 1.502127 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_8__Extra_0 Seg1_dend_6 40.675 15.95594 -24.18662 55.73785 21.33232 -31.51975 0.96 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_8 Seg0_dend_8__Extra_0 70.8007 26.70871 -38.85289 0.96 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_8__Extra_0 Seg0_dend_8 85.86356 32.08509 -46.18602 0.96 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_8 Seg1_dend_8__Extra_0 100.9264 37.46148 -53.51915 0.96 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_7__Extra_0 Seg1_dend_6 40.675 15.95594 -24.18662 56.49898 29.32637 -31.41554 0.9271166 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7__Extra_1 Seg0_dend_7__Extra_0 72.32295 42.6968 -38.64445 0.9271166 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7__Extra_2 Seg0_dend_7__Extra_1 88.14693 56.06724 -45.87337 0.9271166 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7 Seg0_dend_7__Extra_2 103.9709 69.43767 -53.10229 0.9271166 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_0 Seg0_dend_7 119.7949 82.8081 -60.3312 0.8078365 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_1 Seg1_dend_7__Extra_0 135.6188 96.17853 -67.56012 0.8078365 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_2 Seg1_dend_7__Extra_1 151.4428 109.549 -74.78904 0.8078365 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7 Seg1_dend_7__Extra_2 167.2668 122.9194 -82.01796 0.8078365 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_1__Extra_0 Seg1_dend_0 20.065 2.29594 -8.336622 18.10104 17.64734 -10.88722 0.8003399 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_1 Seg0_dend_1__Extra_0 16.13708 32.99873 -13.43781 0.8003399 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_1__Extra_0 Seg0_dend_1 14.17313 48.35013 -15.98841 1.075803 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_1 Seg1_dend_1__Extra_0 12.20917 63.70152 -18.53901 1.075803 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_28 Seg1_apic_1 -247.335 115.2259 3.913378 -256.3198 116.9775 -10.65944 1.318122 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_28 Seg0_apic_28 -265.3046 118.7291 -25.23226 1.146876 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_2 Seg1_apic_1 -247.335 115.2259 3.913378 -250.0688 121.6575 2.170698 2.695008 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_2 Seg0_apic_2 -252.8027 128.0891 0.4280176 3.105663 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_16__Extra_0 Seg1_dend_14 -27.185 -100.9941 -39.28662 -27.86004 -119.336 -42.13287 0.9820778 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_16__Extra_1 Seg0_dend_16__Extra_0 -28.53508 -137.6779 -44.97911 0.9820778 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_16__Extra_2 Seg0_dend_16__Extra_1 -29.21012 -156.0198 -47.82535 0.9820778 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_16 Seg0_dend_16__Extra_2 -29.88515 -174.3617 -50.6716 0.9820778 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_16__Extra_0 Seg0_dend_16 -30.56019 -192.7036 -53.51784 0.9276123 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_16__Extra_1 Seg1_dend_16__Extra_0 -31.23523 -211.0455 -56.36408 0.9276123 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_16__Extra_2 Seg1_dend_16__Extra_1 -31.91027 -229.3874 -59.21033 0.9276123 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_16 Seg1_dend_16__Extra_2 -32.58531 -247.7292 -62.05657 0.9276123 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_15__Extra_0 Seg1_dend_14 -27.185 -100.9941 -39.28662 -26.11081 -124.7574 -43.06479 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_15__Extra_1 Seg0_dend_15__Extra_0 -25.03663 -148.5207 -46.84296 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_15__Extra_2 Seg0_dend_15__Extra_1 -23.96244 -172.284 -50.62113 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_15__Extra_3 Seg0_dend_15__Extra_2 -22.88826 -196.0473 -54.3993 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_15__Extra_4 Seg0_dend_15__Extra_3 -21.81407 -219.8106 -58.17746 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_15__Extra_5 Seg0_dend_15__Extra_4 -20.73989 -243.5739 -61.95564 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_15__Extra_6 Seg0_dend_15__Extra_5 -19.6657 -267.3372 -65.7338 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_15 Seg0_dend_15__Extra_6 -18.59152 -291.1005 -69.51197 1.276719 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15__Extra_0 Seg0_dend_15 -17.51733 -314.8638 -73.29014 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15__Extra_1 Seg1_dend_15__Extra_0 -16.44315 -338.6271 -77.06831 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15__Extra_2 Seg1_dend_15__Extra_1 -15.36896 -362.3904 -80.84648 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15__Extra_3 Seg1_dend_15__Extra_2 -14.29478 -386.1537 -84.62465 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15__Extra_4 Seg1_dend_15__Extra_3 -13.22059 -409.917 -88.40282 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15__Extra_5 Seg1_dend_15__Extra_4 -12.14641 -433.6803 -92.18098 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15__Extra_6 Seg1_dend_15__Extra_5 -11.07222 -457.4436 -95.95915 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_15 Seg1_dend_15__Extra_6 -9.998039 -481.2069 -99.73732 0.9430457 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_10__Extra_0 Seg1_dend_8 80.935 30.32594 -43.78662 100.7252 27.99892 -49.2354 0.8567036 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_10 Seg0_dend_10__Extra_0 120.5154 25.6719 -54.68418 0.8567036 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_10__Extra_0 Seg0_dend_10 140.3056 23.34488 -60.13296 0.7955828 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_10 Seg1_dend_10__Extra_0 160.0959 21.01786 -65.58174 0.7955828 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_9__Extra_0 Seg1_dend_8 80.935 30.32594 -43.78662 100.0946 38.29665 -50.20428 0.9281201 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_9__Extra_1 Seg0_dend_9__Extra_0 119.2542 46.26737 -56.62195 0.9281201 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_9 Seg0_dend_9__Extra_1 138.4138 54.23808 -63.03962 0.9281201 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_9__Extra_0 Seg0_dend_9 157.5734 62.20879 -69.45728 0.8769807 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_9__Extra_1 Seg1_dend_9__Extra_0 176.733 70.17951 -75.87495 0.8769807 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_9 Seg1_dend_9__Extra_1 195.8926 78.15022 -82.29262 0.8769807 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_3__Extra_0 Seg1_dend_1 13.905 50.44594 -16.33662 14.08469 69.38464 -15.88739 0.6874834 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_3__Extra_1 Seg0_dend_3__Extra_0 14.26439 88.32335 -15.43816 0.6874834 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_3 Seg0_dend_3__Extra_1 14.44408 107.262 -14.98893 0.6874834 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_3__Extra_0 Seg0_dend_3 14.62377 126.2007 -14.5397 0.6324705 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_3__Extra_1 Seg1_dend_3__Extra_0 14.80346 145.1395 -14.09047 0.6324705 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_3 Seg1_dend_3__Extra_1 14.98315 164.0782 -13.64124 0.6324705 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_2__Extra_0 Seg1_dend_1 13.905 50.44594 -16.33662 17.78026 70.11857 -20.50621 0.7918355 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_2__Extra_1 Seg0_dend_2__Extra_0 21.65552 89.7912 -24.67579 0.7918355 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_2__Extra_2 Seg0_dend_2__Extra_1 25.53078 109.4638 -28.84538 0.7918355 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_2__Extra_3 Seg0_dend_2__Extra_2 29.40604 129.1364 -33.01496 0.7918355 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_2__Extra_4 Seg0_dend_2__Extra_3 33.2813 148.8091 -37.18454 0.7918355 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_2__Extra_5 Seg0_dend_2__Extra_4 37.15656 168.4817 -41.35413 0.7918355 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_2 Seg0_dend_2__Extra_5 41.03182 188.1543 -45.52371 0.7918355 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2__Extra_0 Seg0_dend_2 44.90709 207.827 -49.6933 0.7168761 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2__Extra_1 Seg1_dend_2__Extra_0 48.78234 227.4996 -53.86288 0.7168761 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2__Extra_2 Seg1_dend_2__Extra_1 52.6576 247.1722 -58.03246 0.7168761 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2__Extra_3 Seg1_dend_2__Extra_2 56.53287 266.8448 -62.20205 0.7168761 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2__Extra_4 Seg1_dend_2__Extra_3 60.40813 286.5175 -66.37163 0.7168761 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2__Extra_5 Seg1_dend_2__Extra_4 64.28339 306.1901 -70.54121 0.7168761 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2 Seg1_dend_2__Extra_5 68.15865 325.8627 -74.7108 0.7168761 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_10 Seg1_apic_2 -252.355 127.0359 0.713378 -246.4987 133.4361 -5.469248 1.439884 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_10 Seg0_apic_10 -240.6424 139.8363 -11.65187 1.314106 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_3 Seg1_apic_2 -252.355 127.0359 0.713378 -255.7599 129.27 -3.653446 1.740943 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_3 Seg0_apic_3 -259.1647 131.504 -8.020269 1.641953 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_12 Seg1_dend_10 146.675 22.59594 -61.88662 149.6191 20.84138 -62.71929 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_12 Seg0_dend_12 152.5632 19.08682 -63.55197 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_11 Seg1_dend_10 146.675 22.59594 -61.88662 148.6783 24.32799 -62.74743 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_11 Seg0_dend_11 150.6817 26.06004 -63.60824 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_5 Seg1_dend_3 14.765 141.0859 -14.18662 18.08807 149.6382 -18.19285 0.7584764 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_5 Seg0_dend_5 21.41113 158.1904 -22.19909 0.6500498 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_4 Seg1_dend_3 14.765 141.0859 -14.18662 9.783621 154.3656 -12.86943 0.5167315 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_4 Seg0_dend_4 4.802241 167.6453 -11.55224 0.4190463 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_27 Seg1_apic_10 -242.125 138.2159 -10.08662 -247.7341 151.2319 -18.86583 0.7025414 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_27 Seg0_apic_27 -253.3432 164.2479 -27.64503 0.5925477 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_11 Seg1_apic_10 -242.125 138.2159 -10.08662 -238.7435 142.7497 -11.12886 1.55 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_11 Seg0_apic_11 -235.362 147.2834 -12.1711 1.55 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_9__Extra_0 Seg1_apic_3 -257.735 130.5659 -6.186622 -257.2698 142.5895 -14.85365 0.89 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_9 Seg0_apic_9__Extra_0 -256.8045 154.6131 -23.52069 0.89 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_9__Extra_0 Seg0_apic_9 -256.3393 166.6367 -32.18772 0.89 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_9 Seg1_apic_9__Extra_0 -255.8741 178.6602 -40.85476 0.89 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_4 Seg1_apic_3 -257.735 130.5659 -6.186622 -260.5783 131.6364 -7.608283 1.381568 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_4 Seg0_apic_4 -263.4216 132.7068 -9.029943 1.265338 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_24 Seg1_apic_11 -236.285 146.0459 -11.88662 -235.9082 149.088 -13.24718 0.8335791 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_24 Seg0_apic_24 -235.5314 152.1301 -14.60773 0.9688327 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_12 Seg1_apic_11 -236.285 146.0459 -11.88662 -228.8989 143.0368 -14.70597 1.405199 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_12 Seg0_apic_12 -221.5127 140.0276 -17.52531 1.159739 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_8 Seg1_apic_4 -262.835 132.4859 -8.736622 -265.1656 138.5794 -15.92858 0.8301836 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_8 Seg0_apic_8 -267.4961 144.6728 -23.12054 0.6482873 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_5 Seg1_apic_4 -262.835 132.4859 -8.736622 -264.6455 131.4116 -14.70533 1.26 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_5 Seg0_apic_5 -266.456 130.3372 -20.67403 1.26 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_26 Seg1_apic_24 -235.745 150.4059 -13.83662 -239.0563 149.6119 -15.5652 0.7309741 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_26 Seg0_apic_26 -242.3676 148.8178 -17.29378 0.6687227 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_25 Seg1_apic_24 -235.745 150.4059 -13.83662 -226.0372 151.9042 -15.0992 0.9419507 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_25 Seg0_apic_25 -216.3294 153.4025 -16.36178 0.7338107 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_23__Extra_0 Seg1_apic_12 -223.055 140.6559 -16.93662 -211.5219 137.9717 -17.13567 0.6849133 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_23 Seg0_apic_23__Extra_0 -199.9887 135.2875 -17.33471 0.6849133 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_23__Extra_0 Seg0_apic_23 -188.4556 132.6032 -17.53375 0.9622349 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_23 Seg1_apic_23__Extra_0 -176.9225 129.919 -17.7328 0.9622349 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_13 Seg1_apic_12 -223.055 140.6559 -16.93662 -220.141 133.2579 -13.6924 1.066015 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_13 Seg0_apic_13 -217.227 125.8599 -10.44817 0.9432644 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_7 Seg1_apic_5 -265.565 130.8659 -17.73662 -268.8405 128.5157 -20.71697 0.96 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_7 Seg0_apic_7 -272.1161 126.1655 -23.69732 0.96 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_6 Seg1_apic_5 -265.565 130.8659 -17.73662 -254.1626 133.0874 -25.86158 1.110653 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_6 Seg0_apic_6 -242.7603 135.309 -33.98653 0.9619039 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_14 Seg1_apic_13 -218.025 127.8859 -11.33662 -217.6116 127.6971 -11.20905 1.11 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_14 Seg0_apic_14 -217.1983 127.5083 -11.08147 1.11 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_22 Seg1_apic_14 -217.215 127.5159 -11.08662 -212.1077 129.4552 -11.51401 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_22 Seg0_apic_22 -207.0005 131.3945 -11.94139 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_15 Seg1_apic_14 -217.215 127.5159 -11.08662 -221.7756 123.9928 -9.36882 1.193643 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_15 Seg0_apic_15 -226.3362 120.4696 -7.651017 1.142618 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_17 Seg1_apic_15 -223.985 122.2859 -8.536622 -227.1341 123.3645 -5.906797 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_17 Seg0_apic_17 -230.2833 124.4431 -3.276973 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_16 Seg1_apic_15 -223.985 122.2859 -8.536622 -242.9221 115.1683 -6.803248 1.024587 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_16 Seg0_apic_16 -261.8592 108.0506 -5.069874 0.8390431 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_21 Seg1_apic_17 -228.715 123.9059 -4.586622 -232.2116 126.9857 -5.986494 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_21 Seg0_apic_21 -235.7081 130.0654 -7.386365 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_18 Seg1_apic_17 -228.715 123.9059 -4.586622 -229.5531 123.0318 -4.406654 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_18 Seg0_apic_18 -230.3913 122.1577 -4.226686 0.81 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_20 Seg1_apic_18 -230.345 122.2059 -4.236622 -230.2597 119.3099 -4.179725 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_20 Seg0_apic_20 -230.1743 116.4138 -4.122828 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_19 Seg1_apic_18 -230.345 122.2059 -4.236622 -232.8801 119.4096 -4.543908 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: LeakConductance (density: 2.55447E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_19 Seg0_apic_19 -235.4152 116.6133 -4.851194 0.59 KA_ChannelML 40 Kdr_ChannelML 1 NaxSH10_ChannelML 400 

