
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.6.1
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 0.62268  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.021649   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global	         EREST_ACT	-0.065  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.065  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*set_compt_param     ELEAK -0.065  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.28231043  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
Seg0_soma none 0 0 0 14.4525 4.54241 -0.00566975 15.91495 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_soma Seg0_soma 28.90499 9.08482 -0.0113395 5.497773 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_0 Seg0_soma 29.13519 8.29372 0.09152561 37.23645 8.033705 0.4229174 3.408902 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_0 Seg0_apic_0 45.3377 7.77369 0.7543092 3.00241 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_11 Seg0_soma 5.17519 9.02372 -1.858474 6.745218 27.70275 -1.105721 1.664689 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_11 Seg0_dend_11 8.315247 46.38178 -0.352968 1.369374 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_0 Seg0_soma 3.27519 5.73372 -5.758474 -0.6945686 13.32692 -5.241579 4.519726 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_0 Seg0_dend_0 -4.664327 20.92011 -4.724683 3.082571 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-6 mS um^-2)
*double_endpoint
Seg0_axon Seg0_soma 1.74519 -3.69628 -4.658474 0.75019 -4.81128 -4.583474 1.523771 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 4000 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
*set_compt_param     ELEAK -0.065  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.1  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
Seg1_axon__Extra_0 Seg0_axon -0.24481 -5.92628 -4.508474 -0.3930646 -25.30889 -4.586605 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_1 Seg1_axon__Extra_0 -0.5413192 -44.69151 -4.664735 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_2 Seg1_axon__Extra_1 -0.6895739 -64.07412 -4.742867 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_3 Seg1_axon__Extra_2 -0.8378284 -83.45673 -4.820997 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_4 Seg1_axon__Extra_3 -0.9860831 -102.8393 -4.899128 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_5 Seg1_axon__Extra_4 -1.134338 -122.222 -4.977259 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_6 Seg1_axon__Extra_5 -1.282592 -141.6046 -5.055389 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_7 Seg1_axon__Extra_6 -1.430847 -160.9872 -5.13352 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_8 Seg1_axon__Extra_7 -1.579102 -180.3698 -5.211651 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_9 Seg1_axon__Extra_8 -1.727356 -199.7524 -5.289782 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_10 Seg1_axon__Extra_9 -1.875611 -219.135 -5.367912 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_11 Seg1_axon__Extra_10 -2.023865 -238.5176 -5.446043 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_12 Seg1_axon__Extra_11 -2.17212 -257.9002 -5.524174 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_13 Seg1_axon__Extra_12 -2.320375 -277.2829 -5.602304 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_14 Seg1_axon__Extra_13 -2.468629 -296.6655 -5.680435 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_15 Seg1_axon__Extra_14 -2.616884 -316.0481 -5.758566 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_16 Seg1_axon__Extra_15 -2.765138 -335.4307 -5.836697 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_17 Seg1_axon__Extra_16 -2.913393 -354.8133 -5.914827 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_18 Seg1_axon__Extra_17 -3.061648 -374.1959 -5.992958 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_19 Seg1_axon__Extra_18 -3.209903 -393.5785 -6.071089 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_20 Seg1_axon__Extra_19 -3.358157 -412.9612 -6.149219 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_21 Seg1_axon__Extra_20 -3.506412 -432.3438 -6.22735 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_22 Seg1_axon__Extra_21 -3.654666 -451.7263 -6.30548 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_23 Seg1_axon__Extra_22 -3.802921 -471.109 -6.383612 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_24 Seg1_axon__Extra_23 -3.951175 -490.4916 -6.461742 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_25 Seg1_axon__Extra_24 -4.09943 -509.8742 -6.539873 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_26 Seg1_axon__Extra_25 -4.247685 -529.2568 -6.618003 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_27 Seg1_axon__Extra_26 -4.395939 -548.6395 -6.696134 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_28 Seg1_axon__Extra_27 -4.544194 -568.022 -6.774265 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_29 Seg1_axon__Extra_28 -4.692448 -587.4047 -6.852396 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_30 Seg1_axon__Extra_29 -4.840703 -606.7872 -6.930526 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_31 Seg1_axon__Extra_30 -4.988957 -626.1699 -7.008657 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_32 Seg1_axon__Extra_31 -5.137212 -645.5524 -7.086787 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_33 Seg1_axon__Extra_32 -5.285467 -664.9351 -7.164918 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_34 Seg1_axon__Extra_33 -5.433722 -684.3177 -7.243049 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_35 Seg1_axon__Extra_34 -5.581976 -703.7004 -7.32118 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_36 Seg1_axon__Extra_35 -5.730231 -723.0829 -7.39931 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_37 Seg1_axon__Extra_36 -5.878486 -742.4656 -7.477441 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_38 Seg1_axon__Extra_37 -6.026741 -761.8482 -7.555572 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_39 Seg1_axon__Extra_38 -6.174995 -781.2308 -7.633703 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_40 Seg1_axon__Extra_39 -6.323249 -800.6134 -7.711833 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_41 Seg1_axon__Extra_40 -6.471504 -819.996 -7.789964 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_42 Seg1_axon__Extra_41 -6.619759 -839.3787 -7.868094 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_43 Seg1_axon__Extra_42 -6.768013 -858.7612 -7.946225 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_44 Seg1_axon__Extra_43 -6.916268 -878.1439 -8.024356 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon__Extra_45 Seg1_axon__Extra_44 -7.064522 -897.5264 -8.102487 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg1_axon Seg1_axon__Extra_45 -7.212777 -916.9091 -8.180617 1.02565 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_0 Seg1_axon -7.361032 -936.2916 -8.258748 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_1 Seg2_axon__Extra_0 -7.509286 -955.6743 -8.336879 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_2 Seg2_axon__Extra_1 -7.657541 -975.0569 -8.415009 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_3 Seg2_axon__Extra_2 -7.805796 -994.4395 -8.49314 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_4 Seg2_axon__Extra_3 -7.95405 -1013.822 -8.571271 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_5 Seg2_axon__Extra_4 -8.102304 -1033.205 -8.649402 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_6 Seg2_axon__Extra_5 -8.25056 -1052.587 -8.727532 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_7 Seg2_axon__Extra_6 -8.398814 -1071.97 -8.805663 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_8 Seg2_axon__Extra_7 -8.54707 -1091.353 -8.883794 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_9 Seg2_axon__Extra_8 -8.695324 -1110.735 -8.961925 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_10 Seg2_axon__Extra_9 -8.843578 -1130.118 -9.040055 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_11 Seg2_axon__Extra_10 -8.991833 -1149.5 -9.118186 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_12 Seg2_axon__Extra_11 -9.140087 -1168.883 -9.196317 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_13 Seg2_axon__Extra_12 -9.288342 -1188.266 -9.274447 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_14 Seg2_axon__Extra_13 -9.436596 -1207.648 -9.352578 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_15 Seg2_axon__Extra_14 -9.58485 -1227.031 -9.430709 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_16 Seg2_axon__Extra_15 -9.733106 -1246.414 -9.50884 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_17 Seg2_axon__Extra_16 -9.881361 -1265.796 -9.58697 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_18 Seg2_axon__Extra_17 -10.02962 -1285.179 -9.6651 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_19 Seg2_axon__Extra_18 -10.17787 -1304.561 -9.743231 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_20 Seg2_axon__Extra_19 -10.32612 -1323.944 -9.821362 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_21 Seg2_axon__Extra_20 -10.47438 -1343.327 -9.899492 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_22 Seg2_axon__Extra_21 -10.62263 -1362.709 -9.977623 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_23 Seg2_axon__Extra_22 -10.77089 -1382.092 -10.05575 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_24 Seg2_axon__Extra_23 -10.91914 -1401.474 -10.13388 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_25 Seg2_axon__Extra_24 -11.0674 -1420.857 -10.21202 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_26 Seg2_axon__Extra_25 -11.21565 -1440.24 -10.29015 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_27 Seg2_axon__Extra_26 -11.36391 -1459.622 -10.36828 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_28 Seg2_axon__Extra_27 -11.51216 -1479.005 -10.44641 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_29 Seg2_axon__Extra_28 -11.66042 -1498.387 -10.52454 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_30 Seg2_axon__Extra_29 -11.80867 -1517.77 -10.60267 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_31 Seg2_axon__Extra_30 -11.95692 -1537.153 -10.6808 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_32 Seg2_axon__Extra_31 -12.10518 -1556.535 -10.75893 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_33 Seg2_axon__Extra_32 -12.25343 -1575.918 -10.83706 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_34 Seg2_axon__Extra_33 -12.40169 -1595.301 -10.91519 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_35 Seg2_axon__Extra_34 -12.54994 -1614.683 -10.99332 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_36 Seg2_axon__Extra_35 -12.6982 -1634.066 -11.07145 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_37 Seg2_axon__Extra_36 -12.84645 -1653.448 -11.14958 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_38 Seg2_axon__Extra_37 -12.99471 -1672.831 -11.22771 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_39 Seg2_axon__Extra_38 -13.14296 -1692.214 -11.30585 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_40 Seg2_axon__Extra_39 -13.29122 -1711.596 -11.38398 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_41 Seg2_axon__Extra_40 -13.43947 -1730.979 -11.46211 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_42 Seg2_axon__Extra_41 -13.58773 -1750.361 -11.54024 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_43 Seg2_axon__Extra_42 -13.73598 -1769.744 -11.61837 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_44 Seg2_axon__Extra_43 -13.88424 -1789.127 -11.6965 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon__Extra_45 Seg2_axon__Extra_44 -14.03249 -1808.509 -11.77463 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 1.0E-8 mS um^-2)
// Cell mechanism: NaxSH0_ChannelML (density: 4.0E-6 mS um^-2)
Seg2_axon Seg2_axon__Extra_45 -14.18074 -1827.892 -11.85276 0.8836299 Kdr_ChannelML 1 KA_ChannelML 400 NaxSH0_ChannelML 4000 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*set_compt_param     ELEAK -0.065  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 0.28231043  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
Seg0_apic_22__Extra_0 Seg1_apic_0 45.02519 7.78372 0.7415256 57.68384 -12.39574 1.199239 0.9769254 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_22 Seg0_apic_22__Extra_0 70.34248 -32.5752 1.656953 0.9769254 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_22__Extra_0 Seg0_apic_22 83.00113 -52.75466 2.114667 1.152715 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_22 Seg1_apic_22__Extra_0 95.65978 -72.93412 2.572381 1.152715 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_1 Seg1_apic_0 45.02519 7.78372 0.7415256 67.04504 8.564764 -0.9879287 2.926067 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_1 Seg0_apic_1 89.0649 9.345808 -2.717383 2.529089 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_6__Extra_0 Seg1_dend_0 -4.40481 20.42372 -4.758474 3.120622 45.26341 -4.196229 1.064948 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_6 Seg0_dend_6__Extra_0 10.64605 70.1031 -3.633985 1.064948 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_6__Extra_0 Seg0_dend_6 18.17149 94.94279 -3.07174 1.161009 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_6 Seg1_dend_6__Extra_0 25.69692 119.7825 -2.509495 1.161009 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_1 Seg1_dend_0 -4.40481 20.42372 -4.758474 -9.33606 29.19443 -9.307597 2.539794 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_1 Seg0_dend_1 -14.26731 37.96514 -13.85672 2.370619 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_21__Extra_0 Seg1_apic_1 84.49519 9.183721 -2.358474 107.7514 -8.598134 -1.822345 1.372137 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_21__Extra_1 Seg0_apic_21__Extra_0 131.0077 -26.37999 -1.286216 1.372137 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_21__Extra_2 Seg0_apic_21__Extra_1 154.2639 -44.16185 -0.7500876 1.372137 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_21 Seg0_apic_21__Extra_2 177.5202 -61.9437 -0.2139587 1.372137 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_21__Extra_0 Seg0_apic_21 200.7764 -79.72556 0.3221701 1.010533 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_21__Extra_1 Seg1_apic_21__Extra_0 224.0327 -97.50741 0.858299 1.010533 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_21__Extra_2 Seg1_apic_21__Extra_1 247.2889 -115.2893 1.394428 1.010533 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_21 Seg1_apic_21__Extra_2 270.5452 -133.0711 1.930557 1.010533 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_2__Extra_0 Seg1_apic_1 84.49519 9.183721 -2.358474 127.6388 27.44315 -2.521311 2.905215 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_2 Seg0_apic_2__Extra_0 170.7824 45.70259 -2.684148 2.905215 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_2__Extra_0 Seg0_apic_2 213.926 63.96202 -2.846985 2.010583 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_2 Seg1_apic_2__Extra_0 257.0696 82.22146 -3.009822 2.010583 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_10__Extra_0 Seg1_dend_6 21.69519 106.5737 -2.808474 15.26028 129.4811 -2.959528 1.100297 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_10__Extra_1 Seg0_dend_10__Extra_0 8.825372 152.3885 -3.110583 1.100297 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_10 Seg0_dend_10__Extra_1 2.390463 175.2958 -3.261637 1.100297 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_10__Extra_0 Seg0_dend_10 -4.044446 198.2032 -3.412691 0.9545346 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_10__Extra_1 Seg1_dend_10__Extra_0 -10.47936 221.1106 -3.563745 0.9545346 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_10 Seg1_dend_10__Extra_1 -16.91426 244.0179 -3.714799 0.9545346 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_7__Extra_0 Seg1_dend_6 21.69519 106.5737 -2.808474 -0.950388 131.4717 -3.492401 1.201244 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7__Extra_1 Seg0_dend_7__Extra_0 -23.59597 156.3697 -4.176328 1.201244 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7__Extra_2 Seg0_dend_7__Extra_1 -46.24154 181.2677 -4.860255 1.201244 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7__Extra_3 Seg0_dend_7__Extra_2 -68.88712 206.1656 -5.544182 1.201244 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7__Extra_4 Seg0_dend_7__Extra_3 -91.53268 231.0636 -6.228108 1.201244 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_7 Seg0_dend_7__Extra_4 -114.1783 255.9616 -6.912035 1.201244 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_0 Seg0_dend_7 -136.8238 280.8596 -7.595962 0.9450534 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_1 Seg1_dend_7__Extra_0 -159.4694 305.7575 -8.279888 0.9450534 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_2 Seg1_dend_7__Extra_1 -182.115 330.6555 -8.963816 0.9450534 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_3 Seg1_dend_7__Extra_2 -204.7606 355.5535 -9.647742 0.9450534 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7__Extra_4 Seg1_dend_7__Extra_3 -227.4061 380.4515 -10.33167 0.9450534 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_7 Seg1_dend_7__Extra_4 -250.0517 405.3495 -11.0156 0.9450534 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_5 Seg1_dend_1 -12.53481 34.88372 -12.25847 -17.61611 65.32977 -25.6926 1.142225 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_5 Seg0_dend_5 -22.69741 95.77582 -39.12673 0.9002661 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_2__Extra_0 Seg1_dend_1 -12.53481 34.88372 -12.25847 -21.46154 57.37012 -12.58899 1.428035 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_2 Seg0_dend_2__Extra_0 -30.38828 79.85653 -12.9195 1.428035 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2__Extra_0 Seg0_dend_2 -39.31501 102.3429 -13.25002 1.011414 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_2 Seg1_dend_2__Extra_0 -48.24175 124.8293 -13.58053 1.011414 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_16 Seg1_apic_2 243.4652 76.46372 -2.958474 250.9373 80.29845 -3.692031 1.138471 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_16 Seg0_apic_16 258.4095 84.13317 -4.425587 1.373211 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_3 Seg1_apic_2 243.4652 76.46372 -2.958474 252.518 75.14545 -3.808142 1.607098 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_3 Seg0_apic_3 261.5708 73.82717 -4.657809 1.943968 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_9 Seg1_dend_7 -201.8048 352.3037 -9.558475 -224.1956 357.1807 -10.42654 1.030044 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_9 Seg0_dend_9 -246.5864 362.0576 -11.2946 0.9334236 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_8__Extra_0 Seg1_dend_7 -201.8048 352.3037 -9.558475 -216.7754 367.1343 -11.19205 1.029535 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_dend_8 Seg0_dend_8__Extra_0 -231.7459 381.9648 -12.82563 1.029535 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_8__Extra_0 Seg0_dend_8 -246.7165 396.7953 -14.4592 0.9360233 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_8 Seg1_dend_8__Extra_0 -261.687 411.6259 -16.09278 0.9360233 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_4 Seg1_dend_2 -43.59481 113.1237 -13.40847 -40.29695 114.4584 -14.54567 0.89 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_4 Seg0_dend_4 -36.9991 115.7931 -15.68286 0.89 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_dend_3 Seg1_dend_2 -43.59481 113.1237 -13.40847 -73.33092 119.2102 -22.37466 0.9646388 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_dend_3 Seg0_dend_3 -103.067 125.2966 -31.34085 0.8963802 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_20__Extra_0 Seg1_apic_16 258.2352 84.04372 -4.408474 283.7704 95.23929 -7.186811 0.8681812 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg0_apic_20 Seg0_apic_20__Extra_0 309.3055 106.4349 -9.965149 0.8681812 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_20__Extra_0 Seg0_apic_20 334.8408 117.6304 -12.74349 0.6633518 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_20 Seg1_apic_20__Extra_0 360.3759 128.826 -15.52182 0.6633518 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_17 Seg1_apic_16 258.2352 84.04372 -4.408474 271.9191 97.39455 -5.813826 1.107518 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_17 Seg0_apic_17 285.6031 110.7454 -7.219177 0.9263 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_13 Seg1_apic_3 261.0452 73.90372 -4.608475 264.3379 69.36436 -5.187073 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_13 Seg0_apic_13 267.6307 64.82499 -5.765671 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_4 Seg1_apic_3 261.0452 73.90372 -4.608475 268.2442 69.94698 -6.448821 1.621072 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_4 Seg0_apic_4 275.4432 65.99023 -8.289166 1.801482 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_19 Seg1_apic_17 284.5252 109.6937 -7.108475 285.3456 122.6028 -6.632125 0.89 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_19 Seg0_apic_19 286.1659 135.5119 -6.155776 0.89 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_18 Seg1_apic_17 284.5252 109.6937 -7.108475 288.2321 122.1407 -7.39008 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_18 Seg0_apic_18 291.9391 134.5877 -7.671687 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_15 Seg1_apic_13 267.3052 65.27372 -5.708475 268.3517 61.89763 -5.655888 0.8297742 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_15 Seg0_apic_15 269.3981 58.52154 -5.603301 0.7027429 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_14 Seg1_apic_13 267.3052 65.27372 -5.708475 271.3294 64.07305 -5.937415 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_14 Seg0_apic_14 275.3537 62.87239 -6.166356 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_12 Seg1_apic_4 274.3452 66.59372 -8.008474 276.4332 54.42078 -7.357832 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_12 Seg0_apic_12 278.5211 42.24785 -6.707189 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_5 Seg1_apic_4 274.3452 66.59372 -8.008474 276.8479 65.54713 -9.019676 1.85 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_5 Seg0_apic_5 279.3506 64.50053 -10.03088 1.85 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_11 Seg1_apic_5 279.2952 64.52372 -10.00847 284.4168 54.55075 -10.53867 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_11 Seg0_apic_11 289.5385 44.57777 -11.06886 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_6 Seg1_apic_5 279.2952 64.52372 -10.00847 282.1461 65.10224 -10.79026 0.968224 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_6 Seg0_apic_6 284.997 65.68076 -11.57205 0.8607879 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_10 Seg1_apic_6 284.7652 65.63372 -11.50847 285.5707 69.5338 -11.91413 0.67 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_10 Seg0_apic_10 286.3762 73.43388 -12.31978 0.67 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_7 Seg1_apic_6 284.7652 65.63372 -11.50847 286.5686 65.36955 -11.43227 0.971759 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_7 Seg0_apic_7 288.3721 65.10538 -11.35607 0.8662148 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_9 Seg1_apic_7 288.3152 65.11372 -11.35847 297.1509 71.10939 -11.21504 0.67 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_9 Seg0_apic_9 305.9866 77.10506 -11.0716 0.67 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
*double_endpoint
Seg0_apic_8 Seg1_apic_7 288.3152 65.11372 -11.35847 293.6103 60.55077 -10.58509 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 
*double_endpoint_off

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-7 mS um^-2)
Seg1_apic_8 Seg0_apic_8 298.9053 55.98782 -9.811712 0.81 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 400 

// Cell mechanism: Kdr_ChannelML (density: 1.0E-9 mS um^-2)
// Cell mechanism: KA_ChannelML (density: 4.0E-8 mS um^-2)
// Cell mechanism: LeakConductance (density: 3.5422E-9 mS um^-2)
// Cell mechanism: NaxSH10_ChannelML (density: 4.0E-6 mS um^-2)
Seg0_axon__Extra Seg0_axon -0.24481 -5.92628 -4.508474 1.427155 Kdr_ChannelML 1 KA_ChannelML 40 NaxSH10_ChannelML 4000 

